name: TruffleHog Scheduled Scan All Branches Recent Commits

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual runs

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches and full history

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog

      - name: Run TruffleHog Scan on Recent Commits
        run: |
          echo "Starting TruffleHog scan on recent commits..." > trufflehog_raw_output.txt
          latest_commit=$(git rev-parse HEAD)
          previous_commit=$(git rev-parse HEAD~5) # Scan the last 5 commits
          trufflehog --regex --entropy=True --since_commit=$previous_commit $(git rev-parse --show-toplevel) >> trufflehog_raw_output.txt || true
        
      - name: Process TruffleHog Report to Group Results by File
        run: |
          echo "Processing raw TruffleHog output to group by file..."
          awk '/Reason: / {reason=$0} /Filepath: / {file=$0} /@@/ {print file ORS reason ORS $0 ORS "~~~~~~~~~~~~~~~~~~~~~"}' trufflehog_raw_output.txt | sort | uniq > trufflehog_report.txt    

      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-report
          path: trufflehog_report.txt
