name: TruffleHog Scheduled Scan

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual runs

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main  # Checkout the main branch
          fetch-depth: 0  # Fetch full history to ensure complete scan

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog

      - name: Run TruffleHog Scan on Main Branch
        run: |
          echo "Starting TruffleHog scan on main branch..." > trufflehog_report.txt
          trufflehog --regex --entropy=True $(git rev-parse --show-toplevel) >> trufflehog_report.txt || true

      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-report
          path: trufflehog_report.txt
