name: TruffleHog Scheduled Scan

on:
  schedule:
    # Runs every day at midnight (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Allows manual runs

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all branches and full history

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog

      - name: Run TruffleHog Scan on All Branches
        run: |
          set +e  # Disable bash strict mode to allow continuation on error
          echo "Starting TruffleHog scan on all branches..." > trufflehog_report.txt
          for branch in $(git branch -r | grep -v '\->'); do
            branch_name=${branch#origin/}
            echo "Checking out branch: $branch_name" >> trufflehog_report.txt
            if [ "$branch_name" != "$(git rev-parse --abbrev-ref HEAD)" ]; then
              git checkout $branch_name || {
                echo "Failed to checkout branch: $branch_name" >> trufflehog_report.txt
                continue
              }
            fi
            echo "Running TruffleHog on branch: $branch_name" >> trufflehog_report.txt
            trufflehog --regex --entropy=True $(git rev-parse --show-toplevel) >> trufflehog_report.txt || {
              echo "TruffleHog scan failed on branch: $branch_name" >> trufflehog_report.txt
              continue
            }
          done
          set -e  # Re-enable bash strict mode

      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-report
          path: trufflehog_report.txt
